/*
 * Copyright © 2026 EduVision. All rights reserved.
 *
 * This file is part of EduVision and is original EduVision IP.
 * Draft for human/legal review, not a final legal filing.
 */

-- Ensure base attendance table exists if not already present
create table if not exists public.attendance (
    id bigint generated by default as identity primary key,
    student_id text not null,
    name text,
    class_name text,
    roll_number text,
    date bigint,
    is_present boolean,
    timestamp bigint
);

alter table public.attendance enable row level security;

create policy if not exists "Allow generic read access" on public.attendance
    for select using (true);

create policy if not exists "Allow generic insert access" on public.attendance
    for insert with check (true);

-- Add multi-tenancy and metadata columns to student_details
alter table public.student_details
    add column if not exists school_id uuid references public.schools(school_id),
    add column if not exists teacher_id uuid,
    add column if not exists student_name text,
    add column if not exists class_name text;

-- Add multi-tenancy and manual correction columns to attendance
alter table public.attendance
    add column if not exists school_id uuid references public.schools(school_id),
    add column if not exists is_manual boolean default false,
    add column if not exists marked_by text;
