/*
 * Copyright © 2026 EduVision. All rights reserved.
 *
 * This file is part of EduVision and is original EduVision IP.
 * Draft for human/legal review, not a final legal filing.
 */

-- Ensure base attendance table exists if not already present
create table if not exists public.attendance (
    id bigint generated by default as identity primary key,
    student_id text not null,
    name text,
    class_name text,
    roll_number text,
    date bigint,
    is_present boolean,
    timestamp bigint
);

-- Helper function to resolve the current authenticated teacher's school_id
-- Prioritizes authenticated auth.uid() match in public.teachers, then verified claims
create or replace function public.current_teacher_school_id()
returns text
language sql
security definer
stable
as $$
    select coalesce(
        (select school_id::text from public.teachers where auth_user_id = auth.uid() limit 1),
        nullif(current_setting('request.jwt.claims', true)::jsonb -> 'user_metadata' ->> 'school_id', '')::text,
        (select school_id::text from public.teachers where teacher_login_id = (current_setting('request.jwt.claims', true)::jsonb -> 'user_metadata' ->> 'teacher_login_id') and (auth_user_id is null or auth_user_id = auth.uid()) limit 1)
    );
$$;

-- Add multi-tenancy and metadata columns to student_details
alter table public.student_details
    add column if not exists school_id text,
    add column if not exists teacher_id text,
    add column if not exists student_name text,
    add column if not exists class_name text;

-- Add multi-tenancy and manual correction columns to attendance
alter table public.attendance
    add column if not exists school_id text,
    add column if not exists is_manual boolean default false,
    add column if not exists marked_by text;

-- Drop legacy open RLS policies on attendance
drop policy if exists "Allow generic read access" on public.attendance;
drop policy if exists "Allow generic insert access" on public.attendance;
drop policy if exists "Allow generic write access" on public.attendance;

-- Scoped RLS policies on attendance
create policy "Teachers read attendance of their school"
    on public.attendance for select
    using (
        auth.role() = 'authenticated' and school_id = public.current_teacher_school_id()
    );

create policy "Teachers insert attendance for their school"
    on public.attendance for insert
    with check (
        auth.role() = 'authenticated' and (school_id is null or school_id = public.current_teacher_school_id())
    );

create policy "Teachers update attendance for their school"
    on public.attendance for update
    using (
        auth.role() = 'authenticated' and school_id = public.current_teacher_school_id()
    )
    with check (
        auth.role() = 'authenticated' and school_id = public.current_teacher_school_id()
    );

-- Drop legacy open RLS policies on student_details
drop policy if exists "Allow generic read access" on public.student_details;
drop policy if exists "Allow generic write access" on public.student_details;
drop policy if exists "Allow generic update access" on public.student_details;

-- Scoped RLS policies on student_details
create policy "Teachers read student details of their school"
    on public.student_details for select
    using (
        auth.role() = 'authenticated' and school_id = public.current_teacher_school_id()
    );

create policy "Teachers insert student details for their school"
    on public.student_details for insert
    with check (
        auth.role() = 'authenticated' and (school_id is null or school_id = public.current_teacher_school_id())
    );

create policy "Teachers update student details for their school"
    on public.student_details for update
    using (
        auth.role() = 'authenticated' and school_id = public.current_teacher_school_id()
    )
    with check (
        auth.role() = 'authenticated' and school_id = public.current_teacher_school_id()
    );

-- Scoped update policy on schools (public read is preserved for initial registration dropdown)
create policy "Teachers update only their own school"
    on public.schools for update
    using (
        auth.role() = 'authenticated' and school_id = public.current_teacher_school_id()
    )
    with check (
        auth.role() = 'authenticated' and school_id = public.current_teacher_school_id()
    );

